name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version
        id: generate_tag
        run: echo "version=$(cat ./VERSION)" >> $GITHUB_OUTPUT

      - name: Print
        run: |
           echo "${{steps.generate_tag.outputs.version}}"
           env

      - name: Create Release
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ steps.generate_tag.outputs.version }}
