name: Release

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version
        id: generate_tag
        run: echo "version=$(cat ./VERSION)" >> $GITHUB_OUTPUT

        #run: |
        #  version=$(cat ./VERSION)
        #  echo "VERSION=$version"
        #  echo "version=$version" >> $GITHUB_ENV
        #  echo "version=$version" >> $GITHUB_OUTPUT
     
      - name: Print
        run: |
           #echo "The version is ${{ env.version }}"
           echo "${{steps.generate_tag.outputs.version}}"
           env

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.generate_tag.outputs.version }}
          name: Release ${{ steps.generate_tag.outputs.version }}

      #- name: Create Release
        #uses: actions/create-release@v1
      #  uses: release-drafter/release-drafter@v6
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    name: Release ${{ steps.generate_tag.outputs.version }}
          #tag_name: ${{ env.version }}
          #release_name: Release ${{ steps.generate_tag.outputs.version }}
          #body: |
          #  Changes in this Release
          #  - First Change
          #  - Second Change
          #draft: false
          #prerelease: false
